In [10]:
import pprint
import numpy as np
import scipy.linalg   # SciPy Linear Algebra Library

A = np.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
P, L, U = scipy.linalg.lu(A)
lu, piv = scipy.linalg.lu_factor(A)

print "A:"
pprint.pprint(A)

print "P:"
pprint.pprint(P)

print "L:"
pprint.pprint(L)

print "U:"
pprint.pprint(U)

print "lu"
pprint.pprint(lu)

print "piv"
pprint.pprint(piv)

A:
array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])
P:
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])
L:
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ,  0.        ],
       [-0.14285714,  0.21276596,  1.        ,  0.        ],
       [ 0.28571429, -0.72340426,  0.08982036,  1.        ]])
U:
array([[ 7.        ,  3.        , -1.        ,  2.        ],
       [ 0.        ,  6.71428571,  1.42857143, -4.85714286],
       [ 0.        ,  0.        ,  3.55319149,  0.31914894],
       [ 0.        ,  0.        ,  0.        ,  1.88622754]])
lu
array([[ 7.        ,  3.        , -1.        ,  2.        ],
       [ 0.42857143,  6.71428571,  1.42857143, -4.85714286],
       [-0.14285714,  0.21276596,  3.55319149,  0.31914894],
       [ 0.28571429, -0.72340426,  0.08982036,  1.88622754]])
piv
array([0, 1, 2, 3], dtype=in

In [11]:
B = np.array([[1],[2],[3],[4]])

In [14]:
x = np.dot(np.matrix(A).I,B)

In [18]:
x[:3]

matrix([[-1.27619048],
        [ 1.87619048],
        [ 0.57142857]])

In [3]:
X = scipy.linalg.lu_solve((lu,piv), B)

array([[-1.27619048],
       [ 1.87619048],
       [ 0.57142857],
       [ 2.43809524]])

In [4]:
np.dot(A,X)

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.]])

In [5]:
a,b,c = X[0],X[1],X[2]

In [6]:
a

array([-1.27619048])

In [7]:
b

array([ 1.87619048])

In [8]:
c

array([ 0.57142857])